import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';
import { hp, LAYOUT, SHADOWS, SIZES, SPACING, TYPOGRAPHY, wp } from '../global';

export const dashboardStyles = StyleSheet.create({
  container: {
    ...LAYOUT.container,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: SPACING.xl,
  },
  header: {
    backgroundColor: Colors.light.background,
    paddingTop: SPACING.xl * 1.5,
    paddingBottom: SPACING.xl,
    paddingHorizontal: SPACING.containerHorizontal,
  },
  greeting: {
    ...TYPOGRAPHY.h1,
    color: Colors.light.text,
    fontWeight: '800',
    letterSpacing: -0.5,
    marginBottom: SPACING.xs,
  },
  subtitle: {
    ...TYPOGRAPHY.body1,
    color: Colors.light.textSecondary,
    fontWeight: '500',
  },
  headerRow: {
    ...LAYOUT.row,
    ...LAYOUT.spaceBetween,
    ...LAYOUT.alignCenter,
  },
  avatar: {
    width: SIZES.avatar.medium,
    height: SIZES.avatar.medium,
    borderRadius: SIZES.avatar.medium / 2,
    backgroundColor: Colors.light.primary,
    ...LAYOUT.center,
  },
  avatarText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: TYPOGRAPHY.body1.fontSize,
  },
  statsContainer: {
    ...LAYOUT.row,
    paddingHorizontal: SPACING.containerHorizontal,
    gap: SPACING.md,
    marginTop: SPACING.lg,
    marginBottom: SPACING.xl,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: SIZES.border.large,
    padding: SPACING.lg,
    ...LAYOUT.center,
    ...SHADOWS.medium,
    transform: [{ translateY: -SPACING.lg }],
  },
  statNumber: {
    ...TYPOGRAPHY.h2,
    fontWeight: '800',
    color: Colors.light.primary,
    marginBottom: SPACING.xs,
  },
  statLabel: {
    ...TYPOGRAPHY.body2,
    color: Colors.light.textSecondary,
    textAlign: 'center',
    fontWeight: '600',
  },
  statsRow: {
    ...LAYOUT.row,
    paddingHorizontal: SPACING.containerHorizontal,
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  section: {
    marginTop: SPACING.lg,
    paddingHorizontal: SPACING.containerHorizontal,
  },
  sectionHeader: {
    ...LAYOUT.row,
    ...LAYOUT.spaceBetween,
    marginBottom: SPACING.md,
    paddingHorizontal: 0,
  },
  sectionTitle: {
    ...TYPOGRAPHY.h3,
    color: Colors.light.text,
  },
  sectionAction: {
    ...TYPOGRAPHY.body2,
    fontWeight: '600',
    color: Colors.light.primary,
  },
  scheduleItem: {
    marginHorizontal: SPACING.containerHorizontal,
    marginBottom: SPACING.sm,
  },
  scheduleCard: {
    backgroundColor: Colors.light.surface,
    borderRadius: SIZES.border.large,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    borderLeftWidth: 4,
    borderLeftColor: Colors.light.primary,
    ...SHADOWS.small,
  },
  scheduleHeader: {
    ...LAYOUT.row,
    ...LAYOUT.spaceBetween,
    marginBottom: SPACING.sm,
  },
  scheduleSubject: {
    ...TYPOGRAPHY.h4,
    flex: 1,
    color: Colors.light.text,
    fontWeight: '700',
  },
  scheduleTime: {
    ...TYPOGRAPHY.body2,
    fontWeight: '600',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: SIZES.border.small,
    backgroundColor: Colors.light.primary,
    color: '#ffffff',
  },
  scheduleDetails: {
    ...LAYOUT.row,
    ...LAYOUT.spaceBetween,
    marginTop: SPACING.sm,
  },
  scheduleTeacher: {
    ...TYPOGRAPHY.body2,
    color: Colors.light.textSecondary,
    fontWeight: '500',
  },
  scheduleLocation: {
    ...TYPOGRAPHY.body2,
    color: Colors.light.textSecondary,
    fontWeight: '500',
  },
  colorIndicator: {
    width: wp(1),
    height: hp(5),
    borderRadius: SIZES.border.small,
    marginRight: SPACING.sm,
  },
  scheduleInfo: {
    flex: 1,
  },
  typeBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: SIZES.border.small,
    marginLeft: SPACING.sm,
    backgroundColor: Colors.light.accent,
  },
  typeBadgeText: {
    ...TYPOGRAPHY.caption,
    fontWeight: '600',
    color: '#ffffff',
  },
  taskItem: {
    marginHorizontal: SPACING.containerHorizontal,
    marginBottom: SPACING.sm,
  },
  taskCard: {
    backgroundColor: Colors.light.surface,
    borderRadius: SIZES.border.large,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    borderLeftWidth: 4,
    borderLeftColor: Colors.light.secondary,
    ...SHADOWS.small,
  },
  taskHeader: {
    ...LAYOUT.row,
    ...LAYOUT.spaceBetween,
    marginBottom: SPACING.sm,
  },
  taskTitle: {
    ...TYPOGRAPHY.h4,
    flex: 1,
    marginRight: SPACING.sm,
    color: Colors.light.text,
    fontWeight: '700',
  },
  taskPriority: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: SIZES.border.medium,
    minWidth: wp(20),
    ...LAYOUT.center,
    ...SHADOWS.small,
  },
  taskPriorityText: {
    ...TYPOGRAPHY.caption,
    fontWeight: '600',
    color: '#ffffff',
  },
  taskInfo: {
    flex: 1,
    marginRight: SPACING.sm,
  },
  taskSubject: {
    ...TYPOGRAPHY.body2,
    color: Colors.light.textSecondary,
    marginBottom: SPACING.xs,
  },
  taskDue: {
    ...TYPOGRAPHY.body2,
    fontWeight: '500',
    color: Colors.light.text,
  },
  taskDueDate: {
    ...TYPOGRAPHY.body2,
    fontWeight: '500',
    color: Colors.light.warning,
  },
  priorityIndicator: {
    width: wp(1),
    height: hp(5),
    borderRadius: SIZES.border.small,
  },
  emptyState: {
    padding: SPACING.xl,
    ...LAYOUT.center,
  },
  emptyText: {
    ...TYPOGRAPHY.body2,
    textAlign: 'center',
    color: Colors.light.textSecondary,
  },
  actionsGrid: {
    ...LAYOUT.row,
    paddingHorizontal: SPACING.containerHorizontal,
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  actionCard: {
    flex: 1,
    minHeight: hp(10),
    backgroundColor: Colors.light.surface,
    borderRadius: SIZES.border.medium,
    ...SHADOWS.small,
  },
  actionContent: {
    ...LAYOUT.center,
    flex: 1,
    padding: SPACING.md,
  },
  actionText: {
    ...TYPOGRAPHY.body2,
    fontWeight: '600',
    marginTop: SPACING.xs,
    color: Colors.light.text,
    textAlign: 'center',
  },
});
